apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8srequiredlabels-template.yaml
  - k8sdisallowlatest-template.yaml
  - k8srequiredresources-template.yaml
  - k8sdisallowprivileged-template.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
