apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - providers/provider-kubernetes.yaml
  - providers/providerconfig-incluster.yaml
  - apis/xrd-service.yaml
  - apis/composition-service.yaml
