apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/k8srequiredlabels-template.yaml
  - templates/k8sdisallowlatest-template.yaml
  - templates/k8srequiredresources-template.yaml
  - templates/k8sdisallowprivileged-template.yaml
  - constraints/namespace-required-labels.yaml
  - constraints/disallow-latest-tag.yaml
  - constraints/require-resource-requests-limits.yaml
  - constraints/disallow-privileged.yaml
