apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - crossplane-core.yaml
  - crossplane-config.yaml
  - opa-core.yaml
  - opa-policies.yaml
  - platform.yaml
