apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: idp-control-plane
  namespace: argocd
spec:
  description: Backend-first IDP control plane applications
  sourceRepos:
    - https://github.com/example-org/argocd-practice.git
    - https://charts.crossplane.io/stable
    - https://open-policy-agent.github.io/gatekeeper/charts
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
