apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliant-sample
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliant-sample
  template:
    metadata:
      labels:
        app: compliant-sample
    spec:
      containers:
        - name: app
          image: nginx:1.27.1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
