apiVersion: apps/v1
kind: Deployment
metadata:
  name: noncompliant-latest
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noncompliant-latest
  template:
    metadata:
      labels:
        app: noncompliant-latest
    spec:
      containers:
        - name: app
          image: nginx:latest
