apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-required-labels.yaml
  - disallow-latest-tag.yaml
  - require-resource-requests-limits.yaml
  - disallow-privileged.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
